<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Database\Seeders\Concerns\ResolvesDocentePorNombre;

class CargaAcademicaSeeder extends Seeder
{
    use ResolvesDocentePorNombre;

    /**
     * academico_carga_academica: cruza id_docente_asignatura con id_curso.
     * Formato de cada fila: [docente, materia, curso]
     */
    public function run(): void
    {
        $triples = [
            ['Corina Corpas', 'Biología', 'Octavo A'],
            ['Corina Corpas', 'Biología', 'Octavo B'],
            ['Corina Corpas', 'Biología', 'Noveno A'],
            ['Corina Corpas', 'Biología', 'Noveno B'],
            ['Corina Corpas', 'Biología', 'Decimo A'],
            ['Corina Corpas', 'Biología', 'Decimo B'],
            ['Corina Corpas', 'Biología', 'Undecimo A'],
            ['Corina Corpas', 'Biología', 'Undecimo B'],
            ['Corina Corpas', 'Medio Ambiente', 'Decimo A'],
            ['Corina Corpas', 'Medio Ambiente', 'Decimo B'],
            ['Corina Corpas', 'Medio Ambiente', 'Undecimo A'],
            ['Corina Corpas', 'Medio Ambiente', 'Undecimo B'],
            ['Derys Mora', 'English', 'Sexto A'],
            ['Derys Mora', 'English', 'Sexto B'],
            ['Derys Mora', 'English', 'Octavo A'],
            ['Derys Mora', 'English', 'Octavo B'],
            ['Derys Mora', 'Global Perspective', 'Octavo A'],
            ['Derys Mora', 'Global Perspective', 'Octavo B'],
            ['Diana Palma', 'Español', 'Decimo A'],
            ['Diana Palma', 'Español', 'Decimo B'],
            ['Diana Palma', 'Español', 'Undecimo A'],
            ['Diana Palma', 'Español', 'Undecimo B'],
            ['Diógenes Visbal', 'Química', 'Noveno A'],
            ['Diógenes Visbal', 'Química', 'Noveno B'],
            ['Diógenes Visbal', 'Química', 'Decimo A'],
            ['Diógenes Visbal', 'Química', 'Decimo B'],
            ['Diógenes Visbal', 'Química', 'Undecimo A'],
            ['Diógenes Visbal', 'Química', 'Undecimo B'],
            ['Dorian Peña', 'Física', 'Octavo A'],
            ['Dorian Peña', 'Física', 'Octavo B'],
            ['Dorian Peña', 'Física', 'Noveno A'],
            ['Dorian Peña', 'Física', 'Noveno B'],
            ['Dorian Peña', 'Física', 'Decimo A'],
            ['Dorian Peña', 'Física', 'Decimo B'],
            ['Dorian Peña', 'Física', 'Undecimo A'],
            ['Dorian Peña', 'Física', 'Undecimo B'],
            ['Douglas Donado', 'Filosofía', 'Decimo A'],
            ['Douglas Donado', 'Filosofía', 'Decimo B'],
            ['Douglas Donado', 'Religión', 'Sexto A'],
            ['Douglas Donado', 'Religión', 'Sexto B'],
            ['Douglas Donado', 'Religión', 'Septimo A'],
            ['Douglas Donado', 'Religión', 'Septimo B'],
            ['Douglas Donado', 'Religión', 'Octavo A'],
            ['Douglas Donado', 'Religión', 'Octavo B'],
            ['Douglas Donado', 'Religión', 'Noveno A'],
            ['Douglas Donado', 'Religión', 'Noveno B'],
            ['Douglas Donado', 'Ética', 'Sexto A'],
            ['Douglas Donado', 'Ética', 'Sexto B'],
            ['Douglas Donado', 'Ética', 'Septimo A'],
            ['Douglas Donado', 'Ética', 'Septimo B'],
            ['Douglas Donado', 'Ética', 'Octavo A'],
            ['Douglas Donado', 'Ética', 'Octavo B'],
            ['Douglas Donado', 'Ética', 'Noveno A'],
            ['Douglas Donado', 'Ética', 'Noveno B'],
            ['Douglas Donado', 'Ética', 'Decimo A'],
            ['Douglas Donado', 'Ética', 'Decimo B'],
            ['Douglas Donado', 'Ética', 'Undecimo A'],
            ['Douglas Donado', 'Ética', 'Undecimo B'],
            ['Edgar Fuentes', 'Economía y Política', 'Decimo A'],
            ['Edgar Fuentes', 'Economía y Política', 'Decimo B'],
            ['Edgar Fuentes', 'Economía y Política', 'Undecimo A'],
            ['Edgar Fuentes', 'Economía y Política', 'Undecimo B'],
            ['Edgar Fuentes', 'Sociales', 'Quinto B'],
            ['Edgar Fuentes', 'Sociales', 'Noveno A'],
            ['Edgar Fuentes', 'Sociales', 'Noveno B'],
            ['Edgar Fuentes', 'Sociales', 'Decimo A'],
            ['Edgar Fuentes', 'Sociales', 'Decimo B'],
            ['Edgar Fuentes', 'Sociales', 'Undecimo A'],
            ['Edgar Fuentes', 'Sociales', 'Undecimo B'],
            ['Erika Rodríguez', 'Español', 'Septimo A'],
            ['Erika Rodríguez', 'Español', 'Septimo B'],
            ['Erika Rodríguez', 'Español', 'Noveno A'],
            ['Erika Rodríguez', 'Español', 'Noveno B'],
            ['Fadia Ruíz', 'Francés', 'Quinto A'],
            ['Fadia Ruíz', 'Francés', 'Quinto B'],
            ['Fadia Ruíz', 'Francés', 'Sexto A'],
            ['Fadia Ruíz', 'Francés', 'Sexto B'],
            ['Fadia Ruíz', 'Francés', 'Septimo A'],
            ['Fadia Ruíz', 'Francés', 'Septimo B'],
            ['Fadia Ruíz', 'Francés', 'Octavo A'],
            ['Fadia Ruíz', 'Francés', 'Octavo B'],
            ['Fadia Ruíz', 'Francés', 'Noveno A'],
            ['Fadia Ruíz', 'Francés', 'Noveno B'],
            ['Fadia Ruíz', 'Francés', 'Decimo A'],
            ['Fadia Ruíz', 'Francés', 'Decimo B'],
            ['Federico Sánchez', 'Chemistry', 'Octavo A'],
            ['Federico Sánchez', 'Chemistry', 'Octavo B'],
            ['Federico Sánchez', 'Science', 'Sexto A'],
            ['Federico Sánchez', 'Science', 'Sexto B'],
            ['Federico Sánchez', 'Science', 'Septimo A'],
            ['Federico Sánchez', 'Science', 'Septimo B'],
            ['Ingrid Almendrales', 'Español', 'Sexto A'],
            ['Ingrid Almendrales', 'Español', 'Sexto B'],
            ['Ingrid Almendrales', 'Español', 'Octavo A'],
            ['Ingrid Almendrales', 'Español', 'Octavo B'],
            ['Ingrid Almendrales', 'Lectura Crítica', 'Undecimo A'],
            ['Ingrid Almendrales', 'Lectura Crítica', 'Undecimo B'],
            ['Jaime Mejía', 'PE', 'Sexto A'],
            ['Jaime Mejía', 'PE', 'Sexto B'],
            ['John Arrieta', 'English', 'Decimo A'],
            ['John Arrieta', 'English', 'Decimo B'],
            ['John Arrieta', 'English', 'Undecimo A'],
            ['John Arrieta', 'English', 'Undecimo B'],
            ['Juan Pablo García', 'Chemistry', 'Octavo A'],
            ['Juan Pablo García', 'Chemistry', 'Octavo B'],
            ['Juan Pablo García', 'Science', 'Sexto A'],
            ['Juan Pablo García', 'Science', 'Sexto B'],
            ['Juan Pablo García', 'Science', 'Septimo A'],
            ['Juan Pablo García', 'Science', 'Septimo B'],
            ['Katty Mercado', 'Aritmética', 'Sexto A'],
            ['Katty Mercado', 'Aritmética', 'Sexto B'],
            ['Katty Mercado', 'Aritmética', 'Septimo A'],
            ['Katty Mercado', 'Aritmética', 'Septimo B'],
            ['Kenny Cohen', 'Enterprise', 'Noveno A'],
            ['Kenny Cohen', 'Enterprise', 'Noveno B'],
            ['Kenny Cohen', 'Enterprise', 'Decimo A'],
            ['Kenny Cohen', 'Enterprise', 'Decimo B'],
            ['Kenny Cohen', 'Global Perspective', 'Sexto A'],
            ['Kenny Cohen', 'Global Perspective', 'Sexto B'],
            ['Kenny Cohen', 'Global Perspective', 'Septimo A'],
            ['Kenny Cohen', 'Global Perspective', 'Septimo B'],
            ['Linda Cera', 'English', 'Septimo A'],
            ['Linda Cera', 'English', 'Septimo B'],
            ['Linda Cera', 'English', 'Noveno A'],
            ['Linda Cera', 'English', 'Noveno B'],
            ['Linda Cera', 'Global Perspective', 'Noveno A'],
            ['Linda Cera', 'Global Perspective', 'Noveno B'],
            ['Loly Algarín', 'Arts', 'Quinto A'],
            ['Loly Algarín', 'Arts', 'Quinto B'],
            ['Loly Algarín', 'Arts', 'Sexto A'],
            ['Loly Algarín', 'Arts', 'Sexto B'],
            ['Loly Algarín', 'Arts', 'Septimo A'],
            ['Loly Algarín', 'Arts', 'Septimo B'],
            ['Loly Algarín', 'Arts', 'Octavo A'],
            ['Loly Algarín', 'Arts', 'Octavo B'],
            ['Loly Algarín', 'Arts', 'Noveno A'],
            ['Loly Algarín', 'Arts', 'Noveno B'],
            ['Loly Algarín', 'Technical Drawing', 'Decimo A'],
            ['Loly Algarín', 'Technical Drawing', 'Decimo B'],
            ['Loly Algarín', 'Technical Drawing', 'Undecimo A'],
            ['Loly Algarín', 'Technical Drawing', 'Undecimo B'],
            ['Mario Esmeral', 'ICT', 'Quinto A'],
            ['Mario Esmeral', 'ICT', 'Quinto B'],
            ['Mario Esmeral', 'ICT', 'Sexto A'],
            ['Mario Esmeral', 'ICT', 'Sexto B'],
            ['Mario Esmeral', 'ICT', 'Septimo A'],
            ['Mario Esmeral', 'ICT', 'Septimo B'],
            ['Mario Esmeral', 'ICT', 'Octavo A'],
            ['Mario Esmeral', 'ICT', 'Octavo B'],
            ['Mario Esmeral', 'ICT', 'Noveno A'],
            ['Mario Esmeral', 'ICT', 'Noveno B'],
            ['Mario Esmeral', 'ICT', 'Decimo A'],
            ['Mario Esmeral', 'ICT', 'Decimo B'],
            ['Mario Esmeral', 'ICT', 'Undecimo A'],
            ['Mario Esmeral', 'ICT', 'Undecimo B'],
            ['Mary Torres', 'Guidance', 'Sexto A'],
            ['Mary Torres', 'Guidance', 'Sexto B'],
            ['Nilson Santiz', 'PE', 'Septimo A'],
            ['Nilson Santiz', 'PE', 'Septimo B'],
            ['Nilson Santiz', 'PE', 'Octavo A'],
            ['Nilson Santiz', 'PE', 'Octavo B'],
            ['Nilson Santiz', 'PE', 'Noveno A'],
            ['Nilson Santiz', 'PE', 'Noveno B'],
            ['Nilson Santiz', 'PE', 'Decimo A'],
            ['Nilson Santiz', 'PE', 'Decimo B'],
            ['Nilson Santiz', 'PE', 'Undecimo A'],
            ['Nilson Santiz', 'PE', 'Undecimo B'],
            ['Paulo Álvarez', 'Cálculo', 'Undecimo A'],
            ['Paulo Álvarez', 'Cálculo', 'Undecimo B'],
            ['Paulo Álvarez', 'Trigonometría', 'Decimo A'],
            ['Paulo Álvarez', 'Trigonometría', 'Decimo B'],
            ['Samir Peñate', 'Filosofía', 'Undecimo A'],
            ['Samir Peñate', 'Filosofía', 'Undecimo B'],
            ['Samir Peñate', 'Sociales', 'Quinto A'],
            ['Samir Peñate', 'Sociales', 'Sexto A'],
            ['Samir Peñate', 'Sociales', 'Sexto B'],
            ['Samir Peñate', 'Sociales', 'Septimo A'],
            ['Samir Peñate', 'Sociales', 'Septimo B'],
            ['Samir Peñate', 'Sociales', 'Octavo A'],
            ['Samir Peñate', 'Sociales', 'Octavo B'],
            ['Santiago Charris', 'Estadística', 'Decimo A'],
            ['Santiago Charris', 'Estadística', 'Decimo B'],
            ['Santiago Charris', 'Estadística y Geometría', 'Septimo A'],
            ['Santiago Charris', 'Estadística y Geometría', 'Septimo B'],
            ['Santiago Charris', 'Estadística y Geometría', 'Noveno A'],
            ['Santiago Charris', 'Estadística y Geometría', 'Noveno B'],
            ['Santiago Charris', 'Álgebra', 'Octavo A'],
            ['Santiago Charris', 'Álgebra', 'Octavo B'],
            ['Yesid Olivares', 'Estadística', 'Undecimo A'],
            ['Yesid Olivares', 'Estadística', 'Undecimo B'],
            ['Yesid Olivares', 'Estadística y Geometría', 'Sexto A'],
            ['Yesid Olivares', 'Estadística y Geometría', 'Sexto B'],
            ['Yesid Olivares', 'Estadística y Geometría', 'Octavo A'],
            ['Yesid Olivares', 'Estadística y Geometría', 'Octavo B'],
            ['Yesid Olivares', 'Álgebra', 'Noveno A'],
            ['Yesid Olivares', 'Álgebra', 'Noveno B'],
        ];

        foreach ($triples as [$nombreDocente, $nombreMateria, $nombreCurso]) {
            $idDocente = $this->resolverDocenteId($nombreDocente);
            $idAsignatura = DB::table('academico_asignatura')->where('nombre', $nombreMateria)->value('id');
            $idCurso = DB::table('curso')->where('nombre', $nombreCurso)->value('id');

            if (!$idDocente || !$idAsignatura || !$idCurso) {
                continue; // faltan datos base (docente/materia/curso), revisar seeders previos
            }

            $idDocenteAsignatura = DB::table('academico_docente_asignatura')
                ->where('id_docente', $idDocente)
                ->where('id_asignatura', $idAsignatura)
                ->value('id');

            if (!$idDocenteAsignatura) {
                continue;
            }

            DB::table('academico_carga_academica')->updateOrInsert(
                [
                    'id_docente_asignatura' => $idDocenteAsignatura,
                    'id_curso'              => $idCurso,
                ],
                [
                    'activo'     => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ]
            );
        }
    }
}
