<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Usuarios\Usuario;

class CargaAcademicaSeeder extends Seeder
{
    /**
     * academico_carga_academica: cruza id_docente_asignatura con id_curso.
     * Formato de cada fila: [docente, materia, curso]
     */
    public function run(): void
    {
        $triples = [
            ['Corina Corpas', 'Biología', '08A'],
            ['Corina Corpas', 'Biología', '08B'],
            ['Corina Corpas', 'Biología', '09A'],
            ['Corina Corpas', 'Biología', '09B'],
            ['Corina Corpas', 'Biología', '10A'],
            ['Corina Corpas', 'Biología', '10B'],
            ['Corina Corpas', 'Biología', '11A'],
            ['Corina Corpas', 'Biología', '11B'],
            ['Corina Corpas', 'Medio Ambiente', '10A'],
            ['Corina Corpas', 'Medio Ambiente', '10B'],
            ['Corina Corpas', 'Medio Ambiente', '11A'],
            ['Corina Corpas', 'Medio Ambiente', '11B'],
            ['Derys Mora', 'English', '06A'],
            ['Derys Mora', 'English', '06B'],
            ['Derys Mora', 'English', '08A'],
            ['Derys Mora', 'English', '08B'],
            ['Derys Mora', 'Global Perspective', '08A'],
            ['Derys Mora', 'Global Perspective', '08B'],
            ['Diana Palma', 'Español', '10A'],
            ['Diana Palma', 'Español', '10B'],
            ['Diana Palma', 'Español', '11A'],
            ['Diana Palma', 'Español', '11B'],
            ['Diógenes Visbal', 'Química', '09A'],
            ['Diógenes Visbal', 'Química', '09B'],
            ['Diógenes Visbal', 'Química', '10A'],
            ['Diógenes Visbal', 'Química', '10B'],
            ['Diógenes Visbal', 'Química', '11A'],
            ['Diógenes Visbal', 'Química', '11B'],
            ['Dorian Peña', 'Física', '08A'],
            ['Dorian Peña', 'Física', '08B'],
            ['Dorian Peña', 'Física', '09A'],
            ['Dorian Peña', 'Física', '09B'],
            ['Dorian Peña', 'Física', '10A'],
            ['Dorian Peña', 'Física', '10B'],
            ['Dorian Peña', 'Física', '11A'],
            ['Dorian Peña', 'Física', '11B'],
            ['Douglas Donado', 'Filosofía', '10A'],
            ['Douglas Donado', 'Filosofía', '10B'],
            ['Douglas Donado', 'Religión', '06A'],
            ['Douglas Donado', 'Religión', '06B'],
            ['Douglas Donado', 'Religión', '07A'],
            ['Douglas Donado', 'Religión', '07B'],
            ['Douglas Donado', 'Religión', '08A'],
            ['Douglas Donado', 'Religión', '08B'],
            ['Douglas Donado', 'Religión', '09A'],
            ['Douglas Donado', 'Religión', '09B'],
            ['Douglas Donado', 'Ética', '06A'],
            ['Douglas Donado', 'Ética', '06B'],
            ['Douglas Donado', 'Ética', '07A'],
            ['Douglas Donado', 'Ética', '07B'],
            ['Douglas Donado', 'Ética', '08A'],
            ['Douglas Donado', 'Ética', '08B'],
            ['Douglas Donado', 'Ética', '09A'],
            ['Douglas Donado', 'Ética', '09B'],
            ['Douglas Donado', 'Ética', '10A'],
            ['Douglas Donado', 'Ética', '10B'],
            ['Douglas Donado', 'Ética', '11A'],
            ['Douglas Donado', 'Ética', '11B'],
            ['Edgar Fuentes', 'Economía y Política', '10A'],
            ['Edgar Fuentes', 'Economía y Política', '10B'],
            ['Edgar Fuentes', 'Economía y Política', '11A'],
            ['Edgar Fuentes', 'Economía y Política', '11B'],
            ['Edgar Fuentes', 'Sociales', '05B'],
            ['Edgar Fuentes', 'Sociales', '09A'],
            ['Edgar Fuentes', 'Sociales', '09B'],
            ['Edgar Fuentes', 'Sociales', '10A'],
            ['Edgar Fuentes', 'Sociales', '10B'],
            ['Edgar Fuentes', 'Sociales', '11A'],
            ['Edgar Fuentes', 'Sociales', '11B'],
            ['Erika Rodríguez', 'Español', '07A'],
            ['Erika Rodríguez', 'Español', '07B'],
            ['Erika Rodríguez', 'Español', '09A'],
            ['Erika Rodríguez', 'Español', '09B'],
            ['Fadia Ruíz', 'Francés', '05A'],
            ['Fadia Ruíz', 'Francés', '05B'],
            ['Fadia Ruíz', 'Francés', '06A'],
            ['Fadia Ruíz', 'Francés', '06B'],
            ['Fadia Ruíz', 'Francés', '07A'],
            ['Fadia Ruíz', 'Francés', '07B'],
            ['Fadia Ruíz', 'Francés', '08A'],
            ['Fadia Ruíz', 'Francés', '08B'],
            ['Fadia Ruíz', 'Francés', '09A'],
            ['Fadia Ruíz', 'Francés', '09B'],
            ['Fadia Ruíz', 'Francés', '10A'],
            ['Fadia Ruíz', 'Francés', '10B'],
            ['Federico Sánchez', 'Chemistry', '08A'],
            ['Federico Sánchez', 'Chemistry', '08B'],
            ['Federico Sánchez', 'Science', '06A'],
            ['Federico Sánchez', 'Science', '06B'],
            ['Federico Sánchez', 'Science', '07A'],
            ['Federico Sánchez', 'Science', '07B'],
            ['Ingrid Almendrales', 'Español', '06A'],
            ['Ingrid Almendrales', 'Español', '06B'],
            ['Ingrid Almendrales', 'Español', '08A'],
            ['Ingrid Almendrales', 'Español', '08B'],
            ['Ingrid Almendrales', 'Lectura Crítica', '11A'],
            ['Ingrid Almendrales', 'Lectura Crítica', '11B'],
            ['Jaime Mejía', 'PE', '06A'],
            ['Jaime Mejía', 'PE', '06B'],
            ['John Arrieta', 'English', '10A'],
            ['John Arrieta', 'English', '10B'],
            ['John Arrieta', 'English', '11A'],
            ['John Arrieta', 'English', '11B'],
            ['Juan Pablo García', 'Chemistry', '08A'],
            ['Juan Pablo García', 'Chemistry', '08B'],
            ['Juan Pablo García', 'Science', '06A'],
            ['Juan Pablo García', 'Science', '06B'],
            ['Juan Pablo García', 'Science', '07A'],
            ['Juan Pablo García', 'Science', '07B'],
            ['Katty Mercado', 'Aritmética', '06A'],
            ['Katty Mercado', 'Aritmética', '06B'],
            ['Katty Mercado', 'Aritmética', '07A'],
            ['Katty Mercado', 'Aritmética', '07B'],
            ['Kenny Cohen', 'Enterprise', '09A'],
            ['Kenny Cohen', 'Enterprise', '09B'],
            ['Kenny Cohen', 'Enterprise', '10A'],
            ['Kenny Cohen', 'Enterprise', '10B'],
            ['Kenny Cohen', 'Global Perspective', '06A'],
            ['Kenny Cohen', 'Global Perspective', '06B'],
            ['Kenny Cohen', 'Global Perspective', '07A'],
            ['Kenny Cohen', 'Global Perspective', '07B'],
            ['Linda Cera', 'English', '07A'],
            ['Linda Cera', 'English', '07B'],
            ['Linda Cera', 'English', '09A'],
            ['Linda Cera', 'English', '09B'],
            ['Linda Cera', 'Global Perspective', '09A'],
            ['Linda Cera', 'Global Perspective', '09B'],
            ['Loly Algarín', 'Arts', '05A'],
            ['Loly Algarín', 'Arts', '05B'],
            ['Loly Algarín', 'Arts', '06A'],
            ['Loly Algarín', 'Arts', '06B'],
            ['Loly Algarín', 'Arts', '07A'],
            ['Loly Algarín', 'Arts', '07B'],
            ['Loly Algarín', 'Arts', '08A'],
            ['Loly Algarín', 'Arts', '08B'],
            ['Loly Algarín', 'Arts', '09A'],
            ['Loly Algarín', 'Arts', '09B'],
            ['Loly Algarín', 'Technical Drawing', '10A'],
            ['Loly Algarín', 'Technical Drawing', '10B'],
            ['Loly Algarín', 'Technical Drawing', '11A'],
            ['Loly Algarín', 'Technical Drawing', '11B'],
            ['Mario Esmeral', 'ICT', '05A'],
            ['Mario Esmeral', 'ICT', '05B'],
            ['Mario Esmeral', 'ICT', '06A'],
            ['Mario Esmeral', 'ICT', '06B'],
            ['Mario Esmeral', 'ICT', '07A'],
            ['Mario Esmeral', 'ICT', '07B'],
            ['Mario Esmeral', 'ICT', '08A'],
            ['Mario Esmeral', 'ICT', '08B'],
            ['Mario Esmeral', 'ICT', '09A'],
            ['Mario Esmeral', 'ICT', '09B'],
            ['Mario Esmeral', 'ICT', '10A'],
            ['Mario Esmeral', 'ICT', '10B'],
            ['Mario Esmeral', 'ICT', '11A'],
            ['Mario Esmeral', 'ICT', '11B'],
            ['Mary Torres', 'Guidance', '06A'],
            ['Mary Torres', 'Guidance', '06B'],
            ['Nilson Santiz', 'PE', '07A'],
            ['Nilson Santiz', 'PE', '07B'],
            ['Nilson Santiz', 'PE', '08A'],
            ['Nilson Santiz', 'PE', '08B'],
            ['Nilson Santiz', 'PE', '09A'],
            ['Nilson Santiz', 'PE', '09B'],
            ['Nilson Santiz', 'PE', '10A'],
            ['Nilson Santiz', 'PE', '10B'],
            ['Nilson Santiz', 'PE', '11A'],
            ['Nilson Santiz', 'PE', '11B'],
            ['Paulo Álvarez', 'Cálculo', '11A'],
            ['Paulo Álvarez', 'Cálculo', '11B'],
            ['Paulo Álvarez', 'Trigonometría', '10A'],
            ['Paulo Álvarez', 'Trigonometría', '10B'],
            ['Samir Peñate', 'Filosofía', '11A'],
            ['Samir Peñate', 'Filosofía', '11B'],
            ['Samir Peñate', 'Sociales', '05A'],
            ['Samir Peñate', 'Sociales', '06A'],
            ['Samir Peñate', 'Sociales', '06B'],
            ['Samir Peñate', 'Sociales', '07A'],
            ['Samir Peñate', 'Sociales', '07B'],
            ['Samir Peñate', 'Sociales', '08A'],
            ['Samir Peñate', 'Sociales', '08B'],
            ['Santiago Charris', 'Estadística', '10A'],
            ['Santiago Charris', 'Estadística', '10B'],
            ['Santiago Charris', 'Estadística y Geometría', '07A'],
            ['Santiago Charris', 'Estadística y Geometría', '07B'],
            ['Santiago Charris', 'Estadística y Geometría', '09A'],
            ['Santiago Charris', 'Estadística y Geometría', '09B'],
            ['Santiago Charris', 'Álgebra', '08A'],
            ['Santiago Charris', 'Álgebra', '08B'],
            ['Yesid Olivares', 'Estadística', '11A'],
            ['Yesid Olivares', 'Estadística', '11B'],
            ['Yesid Olivares', 'Estadística y Geometría', '06A'],
            ['Yesid Olivares', 'Estadística y Geometría', '06B'],
            ['Yesid Olivares', 'Estadística y Geometría', '08A'],
            ['Yesid Olivares', 'Estadística y Geometría', '08B'],
            ['Yesid Olivares', 'Álgebra', '09A'],
            ['Yesid Olivares', 'Álgebra', '09B'],
        ];

        foreach ($triples as [$nombreDocente, $nombreMateria, $nombreCurso]) {
            $idDocente = Usuario::whereRaw("CONCAT(nombre, ' ', apellido) = ?", [$nombreDocente])->value('id_user');
            $idAsignatura = DB::table('academico_asignatura')->where('nombre', $nombreMateria)->value('id');
            $idCurso = DB::table('curso')->where('nombre', $nombreCurso)->value('id');

            if (!$idDocente || !$idAsignatura || !$idCurso) {
                continue; // faltan datos base (docente/materia/curso), revisar seeders previos
            }

            $idDocenteAsignatura = DB::table('academico_docente_asignatura')
                ->where('id_docente', $idDocente)
                ->where('id_asignatura', $idAsignatura)
                ->value('id');

            if (!$idDocenteAsignatura) {
                continue;
            }

            DB::table('academico_carga_academica')->updateOrInsert(
                [
                    'id_docente_asignatura' => $idDocenteAsignatura,
                    'id_curso'              => $idCurso,
                ],
                [
                    'activo'     => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ]
            );
        }
    }
}
