<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Database\Seeders\Concerns\ResolvesDocentePorNombre;

class HorarioSeeder extends Seeder
{
    use ResolvesDocentePorNombre;

    /**
     * academico_horario_clase: cruza id_carga_academica con id_franja_horaria.
     *
     * Solo se siembran los bloques de TIPO CLASE (docente + materia + curso
     * + día + orden de franja), que son los únicos que tienen un
     * carga_academica real detrás. Formato de cada fila:
     * [docente, materia, curso, id_dia_semana(1-5), orden_franja(1-12)]
     *
     * Los bloques sin curso (Lunch, -X-, Reuniones, Planeación/Capacitación,
     * Elective/Club) NO se siembran aquí -- ver nota al final de la clase.
     */
    public function run(): void
    {
        $clases = [
            ['Corina Corpas', 'Biología', 'Noveno B', 1, 1],
            ['Corina Corpas', 'Biología', 'Octavo A', 1, 2],
            ['Corina Corpas', 'Biología', 'Noveno A', 1, 11],
            ['Corina Corpas', 'Biología', 'Noveno B', 2, 2],
            ['Corina Corpas', 'Biología', 'Octavo A', 2, 6],
            ['Corina Corpas', 'Medio Ambiente', 'Undecimo A', 2, 7],
            ['Corina Corpas', 'Biología', 'Decimo B', 2, 8],
            ['Corina Corpas', 'Biología', 'Decimo A', 2, 12],
            ['Corina Corpas', 'Medio Ambiente', 'Decimo A', 3, 1],
            ['Corina Corpas', 'Biología', 'Undecimo B', 3, 2],
            ['Corina Corpas', 'Biología', 'Undecimo A', 3, 6],
            ['Corina Corpas', 'Biología', 'Octavo B', 3, 11],
            ['Corina Corpas', 'Biología', 'Decimo B', 3, 12],
            ['Corina Corpas', 'Biología', 'Octavo B', 4, 2],
            ['Corina Corpas', 'Biología', 'Noveno A', 4, 6],
            ['Corina Corpas', 'Biología', 'Decimo A', 4, 7],
            ['Corina Corpas', 'Biología', 'Undecimo B', 4, 8],
            ['Corina Corpas', 'Biología', 'Undecimo A', 5, 3],
            ['Corina Corpas', 'Medio Ambiente', 'Decimo B', 5, 8],
            ['Corina Corpas', 'Medio Ambiente', 'Undecimo B', 5, 12],
            ['Derys Mora', 'Global Perspective', 'Octavo A', 1, 1],
            ['Derys Mora', 'English', 'Sexto A', 1, 3],
            ['Derys Mora', 'English', 'Octavo B', 1, 6],
            ['Derys Mora', 'English', 'Octavo A', 1, 7],
            ['Derys Mora', 'English', 'Sexto B', 1, 8],
            ['Derys Mora', 'Global Perspective', 'Octavo B', 1, 12],
            ['Derys Mora', 'Global Perspective', 'Octavo B', 2, 3],
            ['Derys Mora', 'English', 'Octavo B', 2, 6],
            ['Derys Mora', 'English', 'Sexto A', 2, 7],
            ['Derys Mora', 'English', 'Sexto B', 2, 11],
            ['Derys Mora', 'English', 'Octavo A', 2, 12],
            ['Derys Mora', 'English', 'Sexto B', 3, 1],
            ['Derys Mora', 'Global Perspective', 'Octavo A', 3, 2],
            ['Derys Mora', 'English', 'Octavo B', 3, 3],
            ['Derys Mora', 'English', 'Octavo A', 3, 7],
            ['Derys Mora', 'English', 'Sexto A', 3, 8],
            ['Derys Mora', 'English', 'Sexto B', 4, 1],
            ['Derys Mora', 'English', 'Sexto A', 4, 2],
            ['Derys Mora', 'Global Perspective', 'Octavo A', 4, 7],
            ['Derys Mora', 'English', 'Octavo A', 4, 11],
            ['Derys Mora', 'English', 'Octavo B', 4, 12],
            ['Derys Mora', 'English', 'Octavo A', 5, 2],
            ['Derys Mora', 'English', 'Octavo B', 5, 3],
            ['Derys Mora', 'English', 'Sexto B', 5, 6],
            ['Derys Mora', 'Global Perspective', 'Octavo B', 5, 8],
            ['Derys Mora', 'English', 'Sexto A', 5, 12],
            ['Diana Palma', 'Español', 'Decimo B', 1, 1],
            ['Diana Palma', 'Español', 'Undecimo A', 1, 3],
            ['Diana Palma', 'Español', 'Undecimo B', 1, 6],
            ['Diana Palma', 'Español', 'Decimo A', 1, 8],
            ['Diana Palma', 'Español', 'Undecimo B', 2, 1],
            ['Diana Palma', 'Español', 'Decimo A', 2, 2],
            ['Diana Palma', 'Español', 'Undecimo A', 2, 8],
            ['Diana Palma', 'Español', 'Decimo B', 2, 12],
            ['Diana Palma', 'Español', 'Undecimo B', 3, 3],
            ['Diana Palma', 'Español', 'Decimo B', 3, 6],
            ['Diana Palma', 'Español', 'Decimo A', 3, 7],
            ['Diana Palma', 'Español', 'Undecimo A', 3, 8],
            ['Diana Palma', 'Español', 'Decimo A', 4, 6],
            ['Diana Palma', 'Español', 'Undecimo A', 4, 7],
            ['Diana Palma', 'Español', 'Decimo B', 4, 11],
            ['Diana Palma', 'Español', 'Undecimo B', 4, 12],
            ['Diana Palma', 'Español', 'Undecimo B', 5, 2],
            ['Diana Palma', 'Español', 'Decimo B', 5, 6],
            ['Diana Palma', 'Español', 'Decimo A', 5, 7],
            ['Diana Palma', 'Español', 'Undecimo A', 5, 11],
            ['Diógenes Visbal', 'Química', 'Decimo A', 1, 3],
            ['Diógenes Visbal', 'Química', 'Noveno B', 1, 6],
            ['Diógenes Visbal', 'Química', 'Noveno A', 1, 8],
            ['Diógenes Visbal', 'Química', 'Undecimo A', 2, 1],
            ['Diógenes Visbal', 'Química', 'Decimo B', 2, 3],
            ['Diógenes Visbal', 'Química', 'Noveno B', 2, 6],
            ['Diógenes Visbal', 'Química', 'Undecimo B', 2, 11],
            ['Diógenes Visbal', 'Química', 'Decimo B', 3, 1],
            ['Diógenes Visbal', 'Química', 'Noveno A', 3, 7],
            ['Diógenes Visbal', 'Química', 'Undecimo A', 3, 12],
            ['Diógenes Visbal', 'Química', 'Undecimo A', 4, 3],
            ['Diógenes Visbal', 'Química', 'Undecimo B', 4, 6],
            ['Diógenes Visbal', 'Química', 'Decimo A', 4, 11],
            ['Diógenes Visbal', 'Química', 'Undecimo B', 5, 7],
            ['Dorian Peña', 'Física', 'Undecimo B', 1, 2],
            ['Dorian Peña', 'Física', 'Undecimo A', 1, 6],
            ['Dorian Peña', 'Física', 'Octavo B', 1, 11],
            ['Dorian Peña', 'Física', 'Noveno A', 2, 1],
            ['Dorian Peña', 'Física', 'Undecimo B', 2, 3],
            ['Dorian Peña', 'Física', 'Decimo B', 2, 7],
            ['Dorian Peña', 'Física', 'Decimo A', 2, 8],
            ['Dorian Peña', 'Física', 'Noveno B', 2, 12],
            ['Dorian Peña', 'Física', 'Undecimo A', 3, 1],
            ['Dorian Peña', 'Física', 'Decimo A', 3, 2],
            ['Dorian Peña', 'Física', 'Undecimo B', 3, 6],
            ['Dorian Peña', 'Física', 'Decimo B', 3, 7],
            ['Dorian Peña', 'Física', 'Undecimo B', 4, 2],
            ['Dorian Peña', 'Física', 'Undecimo A', 4, 6],
            ['Dorian Peña', 'Física', 'Noveno B', 4, 8],
            ['Dorian Peña', 'Física', 'Decimo B', 4, 12],
            ['Dorian Peña', 'Física', 'Decimo A', 5, 2],
            ['Dorian Peña', 'Física', 'Noveno A', 5, 3],
            ['Dorian Peña', 'Física', 'Octavo A', 5, 8],
            ['Dorian Peña', 'Física', 'Undecimo A', 5, 12],
            ['Douglas Donado', 'Ética', 'Undecimo A', 1, 1],
            ['Douglas Donado', 'Ética', 'Noveno A', 1, 7],
            ['Douglas Donado', 'Ética', 'Septimo B', 1, 11],
            ['Douglas Donado', 'Ética', 'Undecimo B', 1, 12],
            ['Douglas Donado', 'Ética', 'Sexto B', 2, 2],
            ['Douglas Donado', 'Ética', 'Sexto A', 2, 6],
            ['Douglas Donado', 'Ética', 'Octavo A', 2, 7],
            ['Douglas Donado', 'Filosofía', 'Decimo B', 2, 11],
            ['Douglas Donado', 'Religión', 'Septimo A', 3, 3],
            ['Douglas Donado', 'Religión', 'Octavo B', 3, 6],
            ['Douglas Donado', 'Religión', 'Septimo B', 3, 7],
            ['Douglas Donado', 'Religión', 'Sexto B', 3, 11],
            ['Douglas Donado', 'Ética', 'Noveno B', 3, 12],
            ['Douglas Donado', 'Religión', 'Octavo A', 4, 1],
            ['Douglas Donado', 'Ética', 'Septimo A', 4, 2],
            ['Douglas Donado', 'Religión', 'Sexto A', 4, 3],
            ['Douglas Donado', 'Ética', 'Decimo B', 4, 6],
            ['Douglas Donado', 'Ética', 'Decimo A', 4, 8],
            ['Douglas Donado', 'Religión', 'Noveno A', 5, 2],
            ['Douglas Donado', 'Religión', 'Noveno B', 5, 3],
            ['Douglas Donado', 'Ética', 'Octavo B', 5, 7],
            ['Douglas Donado', 'Filosofía', 'Decimo A', 5, 11],
            ['Edgar Fuentes', 'Sociales', 'Decimo A', 1, 1],
            ['Edgar Fuentes', 'Economía y Política', 'Decimo B', 1, 8],
            ['Edgar Fuentes', 'Sociales', 'Undecimo B', 2, 6],
            ['Edgar Fuentes', 'Sociales', 'Undecimo A', 2, 11],
            ['Edgar Fuentes', 'Sociales', 'Quinto B', 3, 1],
            ['Edgar Fuentes', 'Economía y Política', 'Undecimo B', 3, 7],
            ['Edgar Fuentes', 'Sociales', 'Noveno A', 3, 11],
            ['Edgar Fuentes', 'Economía y Política', 'Decimo A', 3, 12],
            ['Edgar Fuentes', 'Sociales', 'Quinto B', 4, 1],
            ['Edgar Fuentes', 'Sociales', 'Noveno B', 4, 6],
            ['Edgar Fuentes', 'Sociales', 'Noveno A', 4, 11],
            ['Edgar Fuentes', 'Economía y Política', 'Undecimo A', 5, 6],
            ['Edgar Fuentes', 'Sociales', 'Noveno B', 5, 7],
            ['Edgar Fuentes', 'Sociales', 'Decimo B', 5, 11],
            ['Erika Rodríguez', 'Español', 'Noveno A', 1, 1],
            ['Erika Rodríguez', 'Español', 'Septimo A', 1, 3],
            ['Erika Rodríguez', 'Español', 'Noveno B', 1, 11],
            ['Erika Rodríguez', 'Español', 'Septimo B', 1, 12],
            ['Erika Rodríguez', 'Español', 'Septimo B', 2, 1],
            ['Erika Rodríguez', 'Español', 'Septimo A', 2, 7],
            ['Erika Rodríguez', 'Español', 'Noveno B', 2, 8],
            ['Erika Rodríguez', 'Español', 'Noveno A', 2, 11],
            ['Erika Rodríguez', 'Español', 'Noveno A', 3, 2],
            ['Erika Rodríguez', 'Español', 'Septimo B', 3, 3],
            ['Erika Rodríguez', 'Español', 'Septimo A', 3, 6],
            ['Erika Rodríguez', 'Español', 'Noveno B', 3, 11],
            ['Erika Rodríguez', 'Español', 'Noveno A', 4, 1],
            ['Erika Rodríguez', 'Español', 'Noveno B', 4, 2],
            ['Erika Rodríguez', 'Español', 'Septimo B', 4, 6],
            ['Erika Rodríguez', 'Español', 'Septimo A', 4, 8],
            ['Erika Rodríguez', 'Español', 'Noveno B', 5, 2],
            ['Erika Rodríguez', 'Español', 'Noveno A', 5, 6],
            ['Erika Rodríguez', 'Español', 'Septimo B', 5, 7],
            ['Erika Rodríguez', 'Español', 'Septimo A', 5, 11],
            ['Fadia Ruíz', 'Francés', 'Octavo B', 1, 1],
            ['Fadia Ruíz', 'Francés', 'Septimo B', 1, 3],
            ['Fadia Ruíz', 'Francés', 'Sexto A', 1, 6],
            ['Fadia Ruíz', 'Francés', 'Noveno B', 1, 8],
            ['Fadia Ruíz', 'Francés', 'Decimo B', 1, 12],
            ['Fadia Ruíz', 'Francés', 'Quinto A', 2, 1],
            ['Fadia Ruíz', 'Francés', 'Quinto B', 2, 2],
            ['Fadia Ruíz', 'Francés', 'Noveno A', 2, 3],
            ['Fadia Ruíz', 'Francés', 'Decimo A', 2, 7],
            ['Fadia Ruíz', 'Francés', 'Septimo A', 2, 8],
            ['Fadia Ruíz', 'Francés', 'Noveno B', 3, 1],
            ['Fadia Ruíz', 'Francés', 'Octavo B', 3, 7],
            ['Fadia Ruíz', 'Francés', 'Octavo A', 3, 8],
            ['Fadia Ruíz', 'Francés', 'Septimo B', 3, 12],
            ['Fadia Ruíz', 'Francés', 'Decimo B', 4, 1],
            ['Fadia Ruíz', 'Francés', 'Octavo A', 4, 3],
            ['Fadia Ruíz', 'Francés', 'Sexto B', 4, 7],
            ['Fadia Ruíz', 'Francés', 'Noveno A', 4, 8],
            ['Fadia Ruíz', 'Francés', 'Sexto B', 5, 2],
            ['Fadia Ruíz', 'Francés', 'Sexto A', 5, 3],
            ['Fadia Ruíz', 'Francés', 'Decimo A', 5, 6],
            ['Fadia Ruíz', 'Francés', 'Septimo A', 5, 8],
            ['Federico Sánchez', 'Chemistry', 'Octavo B', 1, 2],
            ['Federico Sánchez', 'Science', 'Septimo A', 1, 6],
            ['Federico Sánchez', 'Chemistry', 'Octavo A', 1, 11],
            ['Federico Sánchez', 'Science', 'Sexto B', 2, 1],
            ['Federico Sánchez', 'Science', 'Septimo B', 2, 2],
            ['Federico Sánchez', 'Science', 'Septimo A', 2, 11],
            ['Federico Sánchez', 'Science', 'Sexto A', 2, 12],
            ['Federico Sánchez', 'Chemistry', 'Octavo B', 3, 1],
            ['Federico Sánchez', 'Science', 'Sexto A', 3, 2],
            ['Federico Sánchez', 'Science', 'Septimo B', 3, 6],
            ['Federico Sánchez', 'Science', 'Septimo A', 3, 11],
            ['Federico Sánchez', 'Science', 'Sexto B', 4, 2],
            ['Federico Sánchez', 'Chemistry', 'Octavo A', 4, 6],
            ['Federico Sánchez', 'Science', 'Septimo B', 4, 11],
            ['Federico Sánchez', 'Science', 'Septimo A', 5, 2],
            ['Federico Sánchez', 'Science', 'Sexto B', 5, 3],
            ['Federico Sánchez', 'Science', 'Sexto A', 5, 11],
            ['Federico Sánchez', 'Science', 'Septimo B', 5, 12],
            ['Ingrid Almendrales', 'Español', 'Sexto B', 1, 1],
            ['Ingrid Almendrales', 'Español', 'Octavo A', 1, 6],
            ['Ingrid Almendrales', 'Lectura Crítica', 'Undecimo B', 1, 7],
            ['Ingrid Almendrales', 'Español', 'Octavo B', 1, 8],
            ['Ingrid Almendrales', 'Español', 'Sexto A', 1, 12],
            ['Ingrid Almendrales', 'Español', 'Octavo A', 2, 1],
            ['Ingrid Almendrales', 'Español', 'Sexto B', 2, 3],
            ['Ingrid Almendrales', 'Español', 'Sexto A', 2, 11],
            ['Ingrid Almendrales', 'Español', 'Octavo B', 2, 12],
            ['Ingrid Almendrales', 'Español', 'Sexto B', 3, 3],
            ['Ingrid Almendrales', 'Español', 'Octavo A', 3, 6],
            ['Ingrid Almendrales', 'Español', 'Sexto A', 3, 11],
            ['Ingrid Almendrales', 'Español', 'Octavo B', 3, 12],
            ['Ingrid Almendrales', 'Lectura Crítica', 'Undecimo A', 4, 1],
            ['Ingrid Almendrales', 'Español', 'Octavo A', 4, 2],
            ['Ingrid Almendrales', 'Español', 'Sexto B', 4, 6],
            ['Ingrid Almendrales', 'Español', 'Octavo B', 4, 11],
            ['Ingrid Almendrales', 'Español', 'Sexto A', 4, 12],
            ['Ingrid Almendrales', 'Español', 'Sexto A', 5, 6],
            ['Ingrid Almendrales', 'Español', 'Octavo A', 5, 7],
            ['Ingrid Almendrales', 'Español', 'Sexto B', 5, 11],
            ['Ingrid Almendrales', 'Español', 'Octavo B', 5, 12],
            ['Jaime Mejía', 'PE', 'Sexto B', 1, 2],
            ['Jaime Mejía', 'PE', 'Sexto A', 1, 7],
            ['Jhon Arrieta', 'English', 'Undecimo B', 1, 1],
            ['Jhon Arrieta', 'English', 'Decimo A', 1, 6],
            ['Jhon Arrieta', 'English', 'Undecimo A', 1, 8],
            ['Jhon Arrieta', 'English', 'Decimo B', 1, 11],
            ['Jhon Arrieta', 'English', 'Decimo A', 2, 1],
            ['Jhon Arrieta', 'English', 'Undecimo A', 2, 3],
            ['Jhon Arrieta', 'English', 'Decimo B', 2, 6],
            ['Jhon Arrieta', 'English', 'Undecimo B', 2, 8],
            ['Jhon Arrieta', 'English', 'Undecimo A', 3, 3],
            ['Jhon Arrieta', 'English', 'Undecimo B', 3, 8],
            ['Jhon Arrieta', 'English', 'Decimo B', 3, 11],
            ['Jhon Arrieta', 'English', 'Decimo A', 4, 2],
            ['Jhon Arrieta', 'English', 'Decimo B', 4, 3],
            ['Jhon Arrieta', 'English', 'Undecimo B', 4, 7],
            ['Jhon Arrieta', 'English', 'Undecimo A', 4, 8],
            ['Jhon Arrieta', 'English', 'Decimo A', 5, 3],
            ['Jhon Arrieta', 'English', 'Undecimo A', 5, 7],
            ['Jhon Arrieta', 'English', 'Undecimo B', 5, 11],
            ['Juan Pablo García', 'Chemistry', 'Octavo B', 1, 2],
            ['Juan Pablo García', 'Science', 'Septimo A', 1, 6],
            ['Juan Pablo García', 'Chemistry', 'Octavo A', 1, 11],
            ['Juan Pablo García', 'Science', 'Septimo B', 2, 2],
            ['Juan Pablo García', 'Science', 'Sexto A', 3, 2],
            ['Juan Pablo García', 'Science', 'Sexto B', 4, 2],
            ['Katty Mercado', 'Aritmética', 'Septimo B', 1, 2],
            ['Katty Mercado', 'Aritmética', 'Sexto B', 1, 6],
            ['Katty Mercado', 'Aritmética', 'Sexto A', 1, 11],
            ['Katty Mercado', 'Aritmética', 'Septimo A', 1, 12],
            ['Katty Mercado', 'Aritmética', 'Septimo A', 2, 3],
            ['Katty Mercado', 'Aritmética', 'Septimo B', 2, 6],
            ['Katty Mercado', 'Aritmética', 'Sexto A', 2, 8],
            ['Katty Mercado', 'Aritmética', 'Sexto B', 2, 12],
            ['Katty Mercado', 'Aritmética', 'Sexto A', 3, 6],
            ['Katty Mercado', 'Aritmética', 'Septimo A', 3, 7],
            ['Katty Mercado', 'Aritmética', 'Septimo B', 3, 8],
            ['Katty Mercado', 'Aritmética', 'Sexto B', 3, 12],
            ['Katty Mercado', 'Aritmética', 'Sexto A', 4, 1],
            ['Katty Mercado', 'Aritmética', 'Septimo A', 4, 3],
            ['Katty Mercado', 'Aritmética', 'Sexto B', 4, 11],
            ['Katty Mercado', 'Aritmética', 'Septimo B', 4, 12],
            ['Katty Mercado', 'Aritmética', 'Sexto A', 5, 2],
            ['Katty Mercado', 'Aritmética', 'Septimo A', 5, 6],
            ['Katty Mercado', 'Aritmética', 'Sexto B', 5, 8],
            ['Katty Mercado', 'Aritmética', 'Septimo B', 5, 11],
            ['Kenny Cohen', 'Global Perspective', 'Septimo A', 1, 1],
            ['Kenny Cohen', 'Enterprise', 'Decimo B', 1, 2],
            ['Kenny Cohen', 'Global Perspective', 'Sexto B', 1, 11],
            ['Kenny Cohen', 'Enterprise', 'Decimo B', 2, 2],
            ['Kenny Cohen', 'Global Perspective', 'Sexto A', 2, 3],
            ['Kenny Cohen', 'Enterprise', 'Decimo A', 2, 6],
            ['Kenny Cohen', 'Global Perspective', 'Septimo B', 2, 8],
            ['Kenny Cohen', 'Enterprise', 'Noveno A', 2, 12],
            ['Kenny Cohen', 'Global Perspective', 'Septimo B', 3, 1],
            ['Kenny Cohen', 'Enterprise', 'Decimo A', 3, 6],
            ['Kenny Cohen', 'Global Perspective', 'Sexto B', 3, 7],
            ['Kenny Cohen', 'Global Perspective', 'Septimo A', 3, 8],
            ['Kenny Cohen', 'Enterprise', 'Noveno A', 3, 12],
            ['Kenny Cohen', 'Global Perspective', 'Septimo B', 4, 1],
            ['Kenny Cohen', 'Global Perspective', 'Septimo A', 4, 6],
            ['Kenny Cohen', 'Global Perspective', 'Sexto A', 4, 8],
            ['Kenny Cohen', 'Enterprise', 'Noveno B', 4, 12],
            ['Kenny Cohen', 'Enterprise', 'Noveno B', 5, 6],
            ['Kenny Cohen', 'Global Perspective', 'Sexto A', 5, 7],
            ['Kenny Cohen', 'Global Perspective', 'Sexto B', 5, 12],
            ['Linda Cera', 'English', 'Septimo B', 1, 1],
            ['Linda Cera', 'English', 'Noveno A', 1, 2],
            ['Linda Cera', 'English', 'Noveno B', 1, 3],
            ['Linda Cera', 'English', 'Septimo A', 1, 11],
            ['Linda Cera', 'Global Perspective', 'Noveno B', 1, 12],
            ['Linda Cera', 'English', 'Noveno A', 2, 2],
            ['Linda Cera', 'Global Perspective', 'Noveno A', 2, 7],
            ['Linda Cera', 'English', 'Septimo B', 2, 11],
            ['Linda Cera', 'English', 'Septimo A', 2, 12],
            ['Linda Cera', 'English', 'Noveno B', 3, 2],
            ['Linda Cera', 'English', 'Noveno A', 3, 3],
            ['Linda Cera', 'English', 'Septimo B', 3, 11],
            ['Linda Cera', 'English', 'Septimo A', 3, 12],
            ['Linda Cera', 'English', 'Septimo A', 4, 1],
            ['Linda Cera', 'English', 'Septimo B', 4, 2],
            ['Linda Cera', 'Global Perspective', 'Noveno B', 4, 3],
            ['Linda Cera', 'English', 'Noveno A', 4, 7],
            ['Linda Cera', 'English', 'Noveno B', 4, 11],
            ['Linda Cera', 'English', 'Septimo A', 5, 3],
            ['Linda Cera', 'English', 'Septimo B', 5, 6],
            ['Linda Cera', 'English', 'Noveno B', 5, 8],
            ['Linda Cera', 'Global Perspective', 'Noveno A', 5, 12],
            ['Loly Algarín', 'Arts', 'Septimo A', 1, 2],
            ['Loly Algarín', 'Arts', 'Septimo B', 1, 8],
            ['Loly Algarín', 'Technical Drawing', 'Undecimo A', 1, 11],
            ['Loly Algarín', 'Arts', 'Quinto B', 2, 1],
            ['Loly Algarín', 'Arts', 'Quinto A', 2, 2],
            ['Loly Algarín', 'Arts', 'Septimo B', 2, 7],
            ['Loly Algarín', 'Arts', 'Sexto B', 2, 8],
            ['Loly Algarín', 'Arts', 'Octavo B', 2, 11],
            ['Loly Algarín', 'Arts', 'Septimo A', 3, 1],
            ['Loly Algarín', 'Arts', 'Sexto B', 3, 6],
            ['Loly Algarín', 'Technical Drawing', 'Decimo A', 3, 11],
            ['Loly Algarín', 'Arts', 'Sexto A', 3, 12],
            ['Loly Algarín', 'Arts', 'Noveno A', 4, 3],
            ['Loly Algarín', 'Arts', 'Sexto A', 4, 6],
            ['Loly Algarín', 'Technical Drawing', 'Undecimo B', 4, 11],
            ['Loly Algarín', 'Technical Drawing', 'Decimo B', 5, 2],
            ['Loly Algarín', 'Arts', 'Octavo A', 5, 6],
            ['Loly Algarín', 'Arts', 'Noveno B', 5, 11],
            ['Mario Esmeral', 'ICT', 'Quinto B', 1, 1],
            ['Mario Esmeral', 'ICT', 'Quinto A', 1, 2],
            ['Mario Esmeral', 'ICT', 'Septimo B', 1, 7],
            ['Mario Esmeral', 'ICT', 'Septimo A', 1, 8],
            ['Mario Esmeral', 'ICT', 'Octavo B', 2, 1],
            ['Mario Esmeral', 'ICT', 'Octavo A', 2, 2],
            ['Mario Esmeral', 'ICT', 'Noveno B', 2, 7],
            ['Mario Esmeral', 'ICT', 'Noveno A', 2, 8],
            ['Mario Esmeral', 'ICT', 'Octavo A', 3, 1],
            ['Mario Esmeral', 'ICT', 'Octavo B', 3, 2],
            ['Mario Esmeral', 'ICT', 'Sexto A', 3, 7],
            ['Mario Esmeral', 'ICT', 'Sexto B', 3, 8],
            ['Mario Esmeral', 'ICT', 'Decimo A', 4, 1],
            ['Mario Esmeral', 'ICT', 'Decimo B', 4, 2],
            ['Mario Esmeral', 'ICT', 'Sexto A', 4, 7],
            ['Mario Esmeral', 'ICT', 'Sexto B', 4, 8],
            ['Mario Esmeral', 'ICT', 'Undecimo A', 5, 2],
            ['Mario Esmeral', 'ICT', 'Undecimo B', 5, 3],
            ['Mario Esmeral', 'ICT', 'Septimo A', 5, 7],
            ['Mario Esmeral', 'ICT', 'Septimo B', 5, 8],
            ['Mary Torres', 'Guidance', 'Sexto A', 4, 11],
            ['Mary Torres', 'Guidance', 'Sexto B', 4, 12],
            ['Nilson Santiz', 'PE', 'Decimo B', 1, 6],
            ['Nilson Santiz', 'PE', 'Decimo A', 1, 11],
            ['Nilson Santiz', 'PE', 'Septimo A', 2, 1],
            ['Nilson Santiz', 'PE', 'Octavo B', 2, 7],
            ['Nilson Santiz', 'PE', 'Noveno B', 3, 7],
            ['Nilson Santiz', 'PE', 'Undecimo B', 3, 11],
            ['Nilson Santiz', 'PE', 'Septimo B', 4, 7],
            ['Nilson Santiz', 'PE', 'Undecimo A', 4, 11],
            ['Nilson Santiz', 'PE', 'Noveno A', 5, 7],
            ['Nilson Santiz', 'PE', 'Octavo A', 5, 11],
            ['Paulo Álvarez', 'Cálculo', 'Undecimo A', 1, 2],
            ['Paulo Álvarez', 'Trigonometría', 'Decimo B', 1, 3],
            ['Paulo Álvarez', 'Trigonometría', 'Decimo A', 1, 7],
            ['Paulo Álvarez', 'Cálculo', 'Undecimo B', 1, 8],
            ['Paulo Álvarez', 'Trigonometría', 'Decimo B', 2, 1],
            ['Paulo Álvarez', 'Cálculo', 'Undecimo B', 2, 2],
            ['Paulo Álvarez', 'Cálculo', 'Undecimo A', 2, 6],
            ['Paulo Álvarez', 'Trigonometría', 'Decimo A', 2, 11],
            ['Paulo Álvarez', 'Cálculo', 'Undecimo B', 3, 1],
            ['Paulo Álvarez', 'Cálculo', 'Undecimo A', 3, 2],
            ['Paulo Álvarez', 'Trigonometría', 'Decimo B', 3, 3],
            ['Paulo Álvarez', 'Trigonometría', 'Decimo A', 3, 8],
            ['Paulo Álvarez', 'Cálculo', 'Undecimo B', 4, 1],
            ['Paulo Álvarez', 'Cálculo', 'Undecimo A', 4, 2],
            ['Paulo Álvarez', 'Trigonometría', 'Decimo A', 4, 3],
            ['Paulo Álvarez', 'Trigonometría', 'Decimo B', 4, 8],
            ['Paulo Álvarez', 'Trigonometría', 'Decimo B', 5, 3],
            ['Paulo Álvarez', 'Cálculo', 'Undecimo B', 5, 6],
            ['Paulo Álvarez', 'Cálculo', 'Undecimo A', 5, 8],
            ['Paulo Álvarez', 'Trigonometría', 'Decimo A', 5, 12],
            ['Samir Peñate', 'Sociales', 'Sexto A', 1, 1],
            ['Samir Peñate', 'Filosofía', 'Undecimo B', 1, 3],
            ['Samir Peñate', 'Sociales', 'Sexto B', 1, 7],
            ['Samir Peñate', 'Sociales', 'Sexto A', 2, 2],
            ['Samir Peñate', 'Sociales', 'Sexto B', 2, 6],
            ['Samir Peñate', 'Sociales', 'Octavo A', 2, 11],
            ['Samir Peñate', 'Sociales', 'Septimo B', 2, 12],
            ['Samir Peñate', 'Sociales', 'Quinto A', 3, 1],
            ['Samir Peñate', 'Filosofía', 'Undecimo A', 3, 7],
            ['Samir Peñate', 'Sociales', 'Octavo A', 3, 11],
            ['Samir Peñate', 'Sociales', 'Quinto A', 4, 1],
            ['Samir Peñate', 'Sociales', 'Octavo B', 4, 6],
            ['Samir Peñate', 'Sociales', 'Septimo A', 4, 11],
            ['Samir Peñate', 'Sociales', 'Septimo B', 5, 2],
            ['Samir Peñate', 'Sociales', 'Octavo B', 5, 11],
            ['Samir Peñate', 'Sociales', 'Septimo A', 5, 12],
            ['Santiago Charris', 'Estadística y Geometría', 'Noveno A', 1, 3],
            ['Santiago Charris', 'Estadística y Geometría', 'Septimo B', 1, 6],
            ['Santiago Charris', 'Álgebra', 'Octavo B', 1, 7],
            ['Santiago Charris', 'Álgebra', 'Octavo A', 1, 8],
            ['Santiago Charris', 'Estadística y Geometría', 'Noveno B', 2, 1],
            ['Santiago Charris', 'Álgebra', 'Octavo B', 2, 2],
            ['Santiago Charris', 'Estadística', 'Decimo A', 2, 3],
            ['Santiago Charris', 'Estadística y Geometría', 'Septimo A', 2, 6],
            ['Santiago Charris', 'Álgebra', 'Octavo A', 2, 8],
            ['Santiago Charris', 'Estadística y Geometría', 'Noveno A', 3, 1],
            ['Santiago Charris', 'Estadística y Geometría', 'Septimo A', 3, 2],
            ['Santiago Charris', 'Álgebra', 'Octavo A', 3, 3],
            ['Santiago Charris', 'Estadística y Geometría', 'Noveno B', 3, 6],
            ['Santiago Charris', 'Álgebra', 'Octavo B', 3, 8],
            ['Santiago Charris', 'Álgebra', 'Octavo B', 4, 1],
            ['Santiago Charris', 'Estadística y Geometría', 'Septimo B', 4, 3],
            ['Santiago Charris', 'Estadística', 'Decimo B', 4, 7],
            ['Santiago Charris', 'Álgebra', 'Octavo A', 4, 8],
            ['Santiago Charris', 'Álgebra', 'Octavo B', 5, 2],
            ['Santiago Charris', 'Álgebra', 'Octavo A', 5, 3],
            ['Santiago Charris', 'Estadística', 'Decimo B', 5, 7],
            ['Santiago Charris', 'Estadística', 'Decimo A', 5, 8],
            ['Yesid Oliveros', 'Álgebra', 'Noveno B', 1, 2],
            ['Yesid Oliveros', 'Álgebra', 'Noveno A', 1, 6],
            ['Yesid Oliveros', 'Estadística', 'Undecimo B', 1, 11],
            ['Yesid Oliveros', 'Estadística', 'Undecimo A', 1, 12],
            ['Yesid Oliveros', 'Estadística y Geometría', 'Sexto A', 2, 1],
            ['Yesid Oliveros', 'Estadística y Geometría', 'Octavo A', 2, 3],
            ['Yesid Oliveros', 'Álgebra', 'Noveno A', 2, 6],
            ['Yesid Oliveros', 'Álgebra', 'Noveno B', 2, 11],
            ['Yesid Oliveros', 'Estadística', 'Undecimo B', 2, 12],
            ['Yesid Oliveros', 'Estadística y Geometría', 'Sexto A', 3, 1],
            ['Yesid Oliveros', 'Estadística y Geometría', 'Sexto B', 3, 2],
            ['Yesid Oliveros', 'Álgebra', 'Noveno B', 3, 3],
            ['Yesid Oliveros', 'Álgebra', 'Noveno A', 3, 6],
            ['Yesid Oliveros', 'Estadística', 'Undecimo A', 3, 11],
            ['Yesid Oliveros', 'Álgebra', 'Noveno B', 4, 1],
            ['Yesid Oliveros', 'Álgebra', 'Noveno A', 4, 2],
            ['Yesid Oliveros', 'Estadística y Geometría', 'Octavo B', 4, 8],
            ['Yesid Oliveros', 'Estadística y Geometría', 'Octavo A', 4, 12],
            ['Yesid Oliveros', 'Estadística y Geometría', 'Octavo B', 5, 6],
            ['Yesid Oliveros', 'Estadística y Geometría', 'Sexto B', 5, 7],
            ['Yesid Oliveros', 'Álgebra', 'Noveno A', 5, 11],
            ['Yesid Oliveros', 'Álgebra', 'Noveno B', 5, 12],
        ];

        $cursoCache = [];
        $esquemaCache = [];
        $franjaCache = [];
        $cargaCache = [];
        $omitidas = 0;

        foreach ($clases as [$nombreDocente, $nombreMateria, $nombreCurso, $diaSemana, $orden]) {
            // --- resolver curso -> nivel -> esquema (con cache) ---
            if (!array_key_exists($nombreCurso, $cursoCache)) {
                $cursoCache[$nombreCurso] = DB::table('curso')->where('nombre', $nombreCurso)->first(['id', 'id_nivel']);
            }
            $curso = $cursoCache[$nombreCurso];
            $idCurso = $curso->id ?? null;
            $idNivel = $curso->id_nivel ?? null;

            if (!isset($esquemaCache[$idNivel])) {
                $esquemaCache[$idNivel] = $idNivel
                    ? DB::table('academico_esquema_horario')->where('id_nivel', $idNivel)->value('id')
                    : null;
            }
            $idEsquema = $esquemaCache[$idNivel] ?? null;

            // --- resolver franja horaria (con cache) ---
            $franjaKey = $idEsquema.'-'.$diaSemana.'-'.$orden;
            if (!isset($franjaCache[$franjaKey])) {
                $franjaCache[$franjaKey] = $idEsquema
                    ? DB::table('academico_franja_horaria')
                        ->where('id_esquema', $idEsquema)
                        ->where('id_dia_semana', $diaSemana)
                        ->where('orden', $orden)
                        ->value('id')
                    : null;
            }
            $idFranja = $franjaCache[$franjaKey];

            // --- resolver carga academica (con cache) ---
            $cargaKey = $nombreDocente.'|'.$nombreMateria.'|'.$nombreCurso;
            if (!isset($cargaCache[$cargaKey])) {
                $idDocente = $this->resolverDocenteId($nombreDocente);
                $idAsignatura = DB::table('academico_asignatura')->where('nombre', $nombreMateria)->value('id');

                $idCarga = null;
                if ($idDocente && $idAsignatura && $idCurso) {
                    $idDocenteAsignatura = DB::table('academico_docente_asignatura')
                        ->where('id_docente', $idDocente)
                        ->where('id_asignatura', $idAsignatura)
                        ->value('id');

                    if ($idDocenteAsignatura) {
                        $idCarga = DB::table('academico_carga_academica')
                            ->where('id_docente_asignatura', $idDocenteAsignatura)
                            ->where('id_curso', $idCurso)
                            ->value('id');
                    }
                }
                $cargaCache[$cargaKey] = $idCarga;
            }
            $idCarga = $cargaCache[$cargaKey];

            if (!$idFranja || !$idCarga) {
                $omitidas++;
                continue;
            }

            DB::table('academico_horario_clase')->updateOrInsert(
                [
                    'id_carga_academica' => $idCarga,
                    'id_franja_horaria'  => $idFranja,
                ],
                [
                    'tipo'       => 'CLASE',
                    'created_at' => now(),
                    'updated_at' => now(),
                ]
            );
        }

        if ($omitidas > 0) {
            $this->command?->warn("Horario: {$omitidas} filas omitidas por datos base faltantes.");
        }
    }
}
