<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Usuarios\Usuario;

class HorarioSeeder extends Seeder
{
    /**
     * academico_horario_clase: cruza id_carga_academica con id_franja_horaria.
     *
     * Solo se siembran los bloques de TIPO CLASE (docente + materia + curso
     * + día + orden de franja), que son los únicos que tienen un
     * carga_academica real detrás. Formato de cada fila:
     * [docente, materia, curso, id_dia_semana(1-5), orden_franja(1-12)]
     *
     * Los bloques sin curso (Lunch, -X-, Reuniones, Planeación/Capacitación,
     * Elective/Club) NO se siembran aquí -- ver nota al final de la clase.
     */
    public function run(): void
    {
        $idAnioEscolar = 1; // debe coincidir con el usado en FranjaHorarioSeeder

        $clases = [
            ['Corina Corpas', 'Biología', '09B', 1, 1],
            ['Corina Corpas', 'Biología', '08A', 1, 2],
            ['Corina Corpas', 'Biología', '09A', 1, 11],
            ['Corina Corpas', 'Biología', '09B', 2, 2],
            ['Corina Corpas', 'Biología', '08A', 2, 6],
            ['Corina Corpas', 'Medio Ambiente', '11A', 2, 7],
            ['Corina Corpas', 'Biología', '10B', 2, 8],
            ['Corina Corpas', 'Biología', '10A', 2, 12],
            ['Corina Corpas', 'Medio Ambiente', '10A', 3, 1],
            ['Corina Corpas', 'Biología', '11B', 3, 2],
            ['Corina Corpas', 'Biología', '11A', 3, 6],
            ['Corina Corpas', 'Biología', '08B', 3, 11],
            ['Corina Corpas', 'Biología', '10B', 3, 12],
            ['Corina Corpas', 'Biología', '08B', 4, 2],
            ['Corina Corpas', 'Biología', '09A', 4, 6],
            ['Corina Corpas', 'Biología', '10A', 4, 7],
            ['Corina Corpas', 'Biología', '11B', 4, 8],
            ['Corina Corpas', 'Biología', '11A', 5, 3],
            ['Corina Corpas', 'Medio Ambiente', '10B', 5, 8],
            ['Corina Corpas', 'Medio Ambiente', '11B', 5, 12],
            ['Derys Mora', 'Global Perspective', '08A', 1, 1],
            ['Derys Mora', 'English', '06A', 1, 3],
            ['Derys Mora', 'English', '08B', 1, 6],
            ['Derys Mora', 'English', '08A', 1, 7],
            ['Derys Mora', 'English', '06B', 1, 8],
            ['Derys Mora', 'Global Perspective', '08B', 1, 12],
            ['Derys Mora', 'Global Perspective', '08B', 2, 3],
            ['Derys Mora', 'English', '08B', 2, 6],
            ['Derys Mora', 'English', '06A', 2, 7],
            ['Derys Mora', 'English', '06B', 2, 11],
            ['Derys Mora', 'English', '08A', 2, 12],
            ['Derys Mora', 'English', '06B', 3, 1],
            ['Derys Mora', 'Global Perspective', '08A', 3, 2],
            ['Derys Mora', 'English', '08B', 3, 3],
            ['Derys Mora', 'English', '08A', 3, 7],
            ['Derys Mora', 'English', '06A', 3, 8],
            ['Derys Mora', 'English', '06B', 4, 1],
            ['Derys Mora', 'English', '06A', 4, 2],
            ['Derys Mora', 'Global Perspective', '08A', 4, 7],
            ['Derys Mora', 'English', '08A', 4, 11],
            ['Derys Mora', 'English', '08B', 4, 12],
            ['Derys Mora', 'English', '08A', 5, 2],
            ['Derys Mora', 'English', '08B', 5, 3],
            ['Derys Mora', 'English', '06B', 5, 6],
            ['Derys Mora', 'Global Perspective', '08B', 5, 8],
            ['Derys Mora', 'English', '06A', 5, 12],
            ['Diana Palma', 'Español', '10B', 1, 1],
            ['Diana Palma', 'Español', '11A', 1, 3],
            ['Diana Palma', 'Español', '11B', 1, 6],
            ['Diana Palma', 'Español', '10A', 1, 8],
            ['Diana Palma', 'Español', '11B', 2, 1],
            ['Diana Palma', 'Español', '10A', 2, 2],
            ['Diana Palma', 'Español', '11A', 2, 8],
            ['Diana Palma', 'Español', '10B', 2, 12],
            ['Diana Palma', 'Español', '11B', 3, 3],
            ['Diana Palma', 'Español', '10B', 3, 6],
            ['Diana Palma', 'Español', '10A', 3, 7],
            ['Diana Palma', 'Español', '11A', 3, 8],
            ['Diana Palma', 'Español', '10A', 4, 6],
            ['Diana Palma', 'Español', '11A', 4, 7],
            ['Diana Palma', 'Español', '10B', 4, 11],
            ['Diana Palma', 'Español', '11B', 4, 12],
            ['Diana Palma', 'Español', '11B', 5, 2],
            ['Diana Palma', 'Español', '10B', 5, 6],
            ['Diana Palma', 'Español', '10A', 5, 7],
            ['Diana Palma', 'Español', '11A', 5, 11],
            ['Diógenes Visbal', 'Química', '10A', 1, 3],
            ['Diógenes Visbal', 'Química', '09B', 1, 6],
            ['Diógenes Visbal', 'Química', '09A', 1, 8],
            ['Diógenes Visbal', 'Química', '11A', 2, 1],
            ['Diógenes Visbal', 'Química', '10B', 2, 3],
            ['Diógenes Visbal', 'Química', '09B', 2, 6],
            ['Diógenes Visbal', 'Química', '11B', 2, 11],
            ['Diógenes Visbal', 'Química', '10B', 3, 1],
            ['Diógenes Visbal', 'Química', '09A', 3, 7],
            ['Diógenes Visbal', 'Química', '11A', 3, 12],
            ['Diógenes Visbal', 'Química', '11A', 4, 3],
            ['Diógenes Visbal', 'Química', '11B', 4, 6],
            ['Diógenes Visbal', 'Química', '10A', 4, 11],
            ['Diógenes Visbal', 'Química', '11B', 5, 7],
            ['Dorian Peña', 'Física', '11B', 1, 2],
            ['Dorian Peña', 'Física', '11A', 1, 6],
            ['Dorian Peña', 'Física', '08B', 1, 11],
            ['Dorian Peña', 'Física', '09A', 2, 1],
            ['Dorian Peña', 'Física', '11B', 2, 3],
            ['Dorian Peña', 'Física', '10B', 2, 7],
            ['Dorian Peña', 'Física', '10A', 2, 8],
            ['Dorian Peña', 'Física', '09B', 2, 12],
            ['Dorian Peña', 'Física', '11A', 3, 1],
            ['Dorian Peña', 'Física', '10A', 3, 2],
            ['Dorian Peña', 'Física', '11B', 3, 6],
            ['Dorian Peña', 'Física', '10B', 3, 7],
            ['Dorian Peña', 'Física', '11B', 4, 2],
            ['Dorian Peña', 'Física', '11A', 4, 6],
            ['Dorian Peña', 'Física', '09B', 4, 8],
            ['Dorian Peña', 'Física', '10B', 4, 12],
            ['Dorian Peña', 'Física', '10A', 5, 2],
            ['Dorian Peña', 'Física', '09A', 5, 3],
            ['Dorian Peña', 'Física', '08A', 5, 8],
            ['Dorian Peña', 'Física', '11A', 5, 12],
            ['Douglas Donado', 'Ética', '11A', 1, 1],
            ['Douglas Donado', 'Ética', '09A', 1, 7],
            ['Douglas Donado', 'Ética', '07B', 1, 11],
            ['Douglas Donado', 'Ética', '11B', 1, 12],
            ['Douglas Donado', 'Ética', '06B', 2, 2],
            ['Douglas Donado', 'Ética', '06A', 2, 6],
            ['Douglas Donado', 'Ética', '08A', 2, 7],
            ['Douglas Donado', 'Filosofía', '10B', 2, 11],
            ['Douglas Donado', 'Religión', '07A', 3, 3],
            ['Douglas Donado', 'Religión', '08B', 3, 6],
            ['Douglas Donado', 'Religión', '07B', 3, 7],
            ['Douglas Donado', 'Religión', '06B', 3, 11],
            ['Douglas Donado', 'Ética', '09B', 3, 12],
            ['Douglas Donado', 'Religión', '08A', 4, 1],
            ['Douglas Donado', 'Ética', '07A', 4, 2],
            ['Douglas Donado', 'Religión', '06A', 4, 3],
            ['Douglas Donado', 'Ética', '10B', 4, 6],
            ['Douglas Donado', 'Ética', '10A', 4, 8],
            ['Douglas Donado', 'Religión', '09A', 5, 2],
            ['Douglas Donado', 'Religión', '09B', 5, 3],
            ['Douglas Donado', 'Ética', '08B', 5, 7],
            ['Douglas Donado', 'Filosofía', '10A', 5, 11],
            ['Edgar Fuentes', 'Sociales', '10A', 1, 1],
            ['Edgar Fuentes', 'Economía y Política', '10B', 1, 8],
            ['Edgar Fuentes', 'Sociales', '11B', 2, 6],
            ['Edgar Fuentes', 'Sociales', '11A', 2, 11],
            ['Edgar Fuentes', 'Sociales', '05B', 3, 1],
            ['Edgar Fuentes', 'Economía y Política', '11B', 3, 7],
            ['Edgar Fuentes', 'Sociales', '09A', 3, 11],
            ['Edgar Fuentes', 'Economía y Política', '10A', 3, 12],
            ['Edgar Fuentes', 'Sociales', '05B', 4, 1],
            ['Edgar Fuentes', 'Sociales', '09B', 4, 6],
            ['Edgar Fuentes', 'Sociales', '09A', 4, 11],
            ['Edgar Fuentes', 'Economía y Política', '11A', 5, 6],
            ['Edgar Fuentes', 'Sociales', '09B', 5, 7],
            ['Edgar Fuentes', 'Sociales', '10B', 5, 11],
            ['Erika Rodríguez', 'Español', '09A', 1, 1],
            ['Erika Rodríguez', 'Español', '07A', 1, 3],
            ['Erika Rodríguez', 'Español', '09B', 1, 11],
            ['Erika Rodríguez', 'Español', '07B', 1, 12],
            ['Erika Rodríguez', 'Español', '07B', 2, 1],
            ['Erika Rodríguez', 'Español', '07A', 2, 7],
            ['Erika Rodríguez', 'Español', '09B', 2, 8],
            ['Erika Rodríguez', 'Español', '09A', 2, 11],
            ['Erika Rodríguez', 'Español', '09A', 3, 2],
            ['Erika Rodríguez', 'Español', '07B', 3, 3],
            ['Erika Rodríguez', 'Español', '07A', 3, 6],
            ['Erika Rodríguez', 'Español', '09B', 3, 11],
            ['Erika Rodríguez', 'Español', '09A', 4, 1],
            ['Erika Rodríguez', 'Español', '09B', 4, 2],
            ['Erika Rodríguez', 'Español', '07B', 4, 6],
            ['Erika Rodríguez', 'Español', '07A', 4, 8],
            ['Erika Rodríguez', 'Español', '09B', 5, 2],
            ['Erika Rodríguez', 'Español', '09A', 5, 6],
            ['Erika Rodríguez', 'Español', '07B', 5, 7],
            ['Erika Rodríguez', 'Español', '07A', 5, 11],
            ['Fadia Ruíz', 'Francés', '08B', 1, 1],
            ['Fadia Ruíz', 'Francés', '07B', 1, 3],
            ['Fadia Ruíz', 'Francés', '06A', 1, 6],
            ['Fadia Ruíz', 'Francés', '09B', 1, 8],
            ['Fadia Ruíz', 'Francés', '10B', 1, 12],
            ['Fadia Ruíz', 'Francés', '05A', 2, 1],
            ['Fadia Ruíz', 'Francés', '05B', 2, 2],
            ['Fadia Ruíz', 'Francés', '09A', 2, 3],
            ['Fadia Ruíz', 'Francés', '10A', 2, 7],
            ['Fadia Ruíz', 'Francés', '07A', 2, 8],
            ['Fadia Ruíz', 'Francés', '09B', 3, 1],
            ['Fadia Ruíz', 'Francés', '08B', 3, 7],
            ['Fadia Ruíz', 'Francés', '08A', 3, 8],
            ['Fadia Ruíz', 'Francés', '07B', 3, 12],
            ['Fadia Ruíz', 'Francés', '10B', 4, 1],
            ['Fadia Ruíz', 'Francés', '08A', 4, 3],
            ['Fadia Ruíz', 'Francés', '06B', 4, 7],
            ['Fadia Ruíz', 'Francés', '09A', 4, 8],
            ['Fadia Ruíz', 'Francés', '06B', 5, 2],
            ['Fadia Ruíz', 'Francés', '06A', 5, 3],
            ['Fadia Ruíz', 'Francés', '10A', 5, 6],
            ['Fadia Ruíz', 'Francés', '07A', 5, 8],
            ['Federico Sánchez', 'Chemistry', '08B', 1, 2],
            ['Federico Sánchez', 'Science', '07A', 1, 6],
            ['Federico Sánchez', 'Chemistry', '08A', 1, 11],
            ['Federico Sánchez', 'Science', '06B', 2, 1],
            ['Federico Sánchez', 'Science', '07B', 2, 2],
            ['Federico Sánchez', 'Science', '07A', 2, 11],
            ['Federico Sánchez', 'Science', '06A', 2, 12],
            ['Federico Sánchez', 'Chemistry', '08B', 3, 1],
            ['Federico Sánchez', 'Science', '06A', 3, 2],
            ['Federico Sánchez', 'Science', '07B', 3, 6],
            ['Federico Sánchez', 'Science', '07A', 3, 11],
            ['Federico Sánchez', 'Science', '06B', 4, 2],
            ['Federico Sánchez', 'Chemistry', '08A', 4, 6],
            ['Federico Sánchez', 'Science', '07B', 4, 11],
            ['Federico Sánchez', 'Science', '07A', 5, 2],
            ['Federico Sánchez', 'Science', '06B', 5, 3],
            ['Federico Sánchez', 'Science', '06A', 5, 11],
            ['Federico Sánchez', 'Science', '07B', 5, 12],
            ['Ingrid Almendrales', 'Español', '06B', 1, 1],
            ['Ingrid Almendrales', 'Español', '08A', 1, 6],
            ['Ingrid Almendrales', 'Lectura Crítica', '11B', 1, 7],
            ['Ingrid Almendrales', 'Español', '08B', 1, 8],
            ['Ingrid Almendrales', 'Español', '06A', 1, 12],
            ['Ingrid Almendrales', 'Español', '08A', 2, 1],
            ['Ingrid Almendrales', 'Español', '06B', 2, 3],
            ['Ingrid Almendrales', 'Español', '06A', 2, 11],
            ['Ingrid Almendrales', 'Español', '08B', 2, 12],
            ['Ingrid Almendrales', 'Español', '06B', 3, 3],
            ['Ingrid Almendrales', 'Español', '08A', 3, 6],
            ['Ingrid Almendrales', 'Español', '06A', 3, 11],
            ['Ingrid Almendrales', 'Español', '08B', 3, 12],
            ['Ingrid Almendrales', 'Lectura Crítica', '11A', 4, 1],
            ['Ingrid Almendrales', 'Español', '08A', 4, 2],
            ['Ingrid Almendrales', 'Español', '06B', 4, 6],
            ['Ingrid Almendrales', 'Español', '08B', 4, 11],
            ['Ingrid Almendrales', 'Español', '06A', 4, 12],
            ['Ingrid Almendrales', 'Español', '06A', 5, 6],
            ['Ingrid Almendrales', 'Español', '08A', 5, 7],
            ['Ingrid Almendrales', 'Español', '06B', 5, 11],
            ['Ingrid Almendrales', 'Español', '08B', 5, 12],
            ['Jaime Mejía', 'PE', '06B', 1, 2],
            ['Jaime Mejía', 'PE', '06A', 1, 7],
            ['John Arrieta', 'English', '11B', 1, 1],
            ['John Arrieta', 'English', '10A', 1, 6],
            ['John Arrieta', 'English', '11A', 1, 8],
            ['John Arrieta', 'English', '10B', 1, 11],
            ['John Arrieta', 'English', '10A', 2, 1],
            ['John Arrieta', 'English', '11A', 2, 3],
            ['John Arrieta', 'English', '10B', 2, 6],
            ['John Arrieta', 'English', '11B', 2, 8],
            ['John Arrieta', 'English', '11A', 3, 3],
            ['John Arrieta', 'English', '11B', 3, 8],
            ['John Arrieta', 'English', '10B', 3, 11],
            ['John Arrieta', 'English', '10A', 4, 2],
            ['John Arrieta', 'English', '10B', 4, 3],
            ['John Arrieta', 'English', '11B', 4, 7],
            ['John Arrieta', 'English', '11A', 4, 8],
            ['John Arrieta', 'English', '10A', 5, 3],
            ['John Arrieta', 'English', '11A', 5, 7],
            ['John Arrieta', 'English', '11B', 5, 11],
            ['Juan Pablo García', 'Chemistry', '08B', 1, 2],
            ['Juan Pablo García', 'Science', '07A', 1, 6],
            ['Juan Pablo García', 'Chemistry', '08A', 1, 11],
            ['Juan Pablo García', 'Science', '07B', 2, 2],
            ['Juan Pablo García', 'Science', '06A', 3, 2],
            ['Juan Pablo García', 'Science', '06B', 4, 2],
            ['Katty Mercado', 'Aritmética', '07B', 1, 2],
            ['Katty Mercado', 'Aritmética', '06B', 1, 6],
            ['Katty Mercado', 'Aritmética', '06A', 1, 11],
            ['Katty Mercado', 'Aritmética', '07A', 1, 12],
            ['Katty Mercado', 'Aritmética', '07A', 2, 3],
            ['Katty Mercado', 'Aritmética', '07B', 2, 6],
            ['Katty Mercado', 'Aritmética', '06A', 2, 8],
            ['Katty Mercado', 'Aritmética', '06B', 2, 12],
            ['Katty Mercado', 'Aritmética', '06A', 3, 6],
            ['Katty Mercado', 'Aritmética', '07A', 3, 7],
            ['Katty Mercado', 'Aritmética', '07B', 3, 8],
            ['Katty Mercado', 'Aritmética', '06B', 3, 12],
            ['Katty Mercado', 'Aritmética', '06A', 4, 1],
            ['Katty Mercado', 'Aritmética', '07A', 4, 3],
            ['Katty Mercado', 'Aritmética', '06B', 4, 11],
            ['Katty Mercado', 'Aritmética', '07B', 4, 12],
            ['Katty Mercado', 'Aritmética', '06A', 5, 2],
            ['Katty Mercado', 'Aritmética', '07A', 5, 6],
            ['Katty Mercado', 'Aritmética', '06B', 5, 8],
            ['Katty Mercado', 'Aritmética', '07B', 5, 11],
            ['Kenny Cohen', 'Global Perspective', '07A', 1, 1],
            ['Kenny Cohen', 'Enterprise', '10B', 1, 2],
            ['Kenny Cohen', 'Global Perspective', '06B', 1, 11],
            ['Kenny Cohen', 'Enterprise', '10B', 2, 2],
            ['Kenny Cohen', 'Global Perspective', '06A', 2, 3],
            ['Kenny Cohen', 'Enterprise', '10A', 2, 6],
            ['Kenny Cohen', 'Global Perspective', '07B', 2, 8],
            ['Kenny Cohen', 'Enterprise', '09A', 2, 12],
            ['Kenny Cohen', 'Global Perspective', '07B', 3, 1],
            ['Kenny Cohen', 'Enterprise', '10A', 3, 6],
            ['Kenny Cohen', 'Global Perspective', '06B', 3, 7],
            ['Kenny Cohen', 'Global Perspective', '07A', 3, 8],
            ['Kenny Cohen', 'Enterprise', '09A', 3, 12],
            ['Kenny Cohen', 'Global Perspective', '07B', 4, 1],
            ['Kenny Cohen', 'Global Perspective', '07A', 4, 6],
            ['Kenny Cohen', 'Global Perspective', '06A', 4, 8],
            ['Kenny Cohen', 'Enterprise', '09B', 4, 12],
            ['Kenny Cohen', 'Enterprise', '09B', 5, 6],
            ['Kenny Cohen', 'Global Perspective', '06A', 5, 7],
            ['Kenny Cohen', 'Global Perspective', '06B', 5, 12],
            ['Linda Cera', 'English', '07B', 1, 1],
            ['Linda Cera', 'English', '09A', 1, 2],
            ['Linda Cera', 'English', '09B', 1, 3],
            ['Linda Cera', 'English', '07A', 1, 11],
            ['Linda Cera', 'Global Perspective', '09B', 1, 12],
            ['Linda Cera', 'English', '09A', 2, 2],
            ['Linda Cera', 'Global Perspective', '09A', 2, 7],
            ['Linda Cera', 'English', '07B', 2, 11],
            ['Linda Cera', 'English', '07A', 2, 12],
            ['Linda Cera', 'English', '09B', 3, 2],
            ['Linda Cera', 'English', '09A', 3, 3],
            ['Linda Cera', 'English', '07B', 3, 11],
            ['Linda Cera', 'English', '07A', 3, 12],
            ['Linda Cera', 'English', '07A', 4, 1],
            ['Linda Cera', 'English', '07B', 4, 2],
            ['Linda Cera', 'Global Perspective', '09B', 4, 3],
            ['Linda Cera', 'English', '09A', 4, 7],
            ['Linda Cera', 'English', '09B', 4, 11],
            ['Linda Cera', 'English', '07A', 5, 3],
            ['Linda Cera', 'English', '07B', 5, 6],
            ['Linda Cera', 'English', '09B', 5, 8],
            ['Linda Cera', 'Global Perspective', '09A', 5, 12],
            ['Loly Algarín', 'Arts', '07A', 1, 2],
            ['Loly Algarín', 'Arts', '07B', 1, 8],
            ['Loly Algarín', 'Technical Drawing', '11A', 1, 11],
            ['Loly Algarín', 'Arts', '05B', 2, 1],
            ['Loly Algarín', 'Arts', '05A', 2, 2],
            ['Loly Algarín', 'Arts', '07B', 2, 7],
            ['Loly Algarín', 'Arts', '06B', 2, 8],
            ['Loly Algarín', 'Arts', '08B', 2, 11],
            ['Loly Algarín', 'Arts', '07A', 3, 1],
            ['Loly Algarín', 'Arts', '06B', 3, 6],
            ['Loly Algarín', 'Technical Drawing', '10A', 3, 11],
            ['Loly Algarín', 'Arts', '06A', 3, 12],
            ['Loly Algarín', 'Arts', '09A', 4, 3],
            ['Loly Algarín', 'Arts', '06A', 4, 6],
            ['Loly Algarín', 'Technical Drawing', '11B', 4, 11],
            ['Loly Algarín', 'Technical Drawing', '10B', 5, 2],
            ['Loly Algarín', 'Arts', '08A', 5, 6],
            ['Loly Algarín', 'Arts', '09B', 5, 11],
            ['Mario Esmeral', 'ICT', '05B', 1, 1],
            ['Mario Esmeral', 'ICT', '05A', 1, 2],
            ['Mario Esmeral', 'ICT', '07B', 1, 7],
            ['Mario Esmeral', 'ICT', '07A', 1, 8],
            ['Mario Esmeral', 'ICT', '08B', 2, 1],
            ['Mario Esmeral', 'ICT', '08A', 2, 2],
            ['Mario Esmeral', 'ICT', '09B', 2, 7],
            ['Mario Esmeral', 'ICT', '09A', 2, 8],
            ['Mario Esmeral', 'ICT', '08A', 3, 1],
            ['Mario Esmeral', 'ICT', '08B', 3, 2],
            ['Mario Esmeral', 'ICT', '06A', 3, 7],
            ['Mario Esmeral', 'ICT', '06B', 3, 8],
            ['Mario Esmeral', 'ICT', '10A', 4, 1],
            ['Mario Esmeral', 'ICT', '10B', 4, 2],
            ['Mario Esmeral', 'ICT', '06A', 4, 7],
            ['Mario Esmeral', 'ICT', '06B', 4, 8],
            ['Mario Esmeral', 'ICT', '11A', 5, 2],
            ['Mario Esmeral', 'ICT', '11B', 5, 3],
            ['Mario Esmeral', 'ICT', '07A', 5, 7],
            ['Mario Esmeral', 'ICT', '07B', 5, 8],
            ['Mary Torres', 'Guidance', '06A', 4, 11],
            ['Mary Torres', 'Guidance', '06B', 4, 12],
            ['Nilson Santiz', 'PE', '10B', 1, 6],
            ['Nilson Santiz', 'PE', '10A', 1, 11],
            ['Nilson Santiz', 'PE', '07A', 2, 1],
            ['Nilson Santiz', 'PE', '08B', 2, 7],
            ['Nilson Santiz', 'PE', '09B', 3, 7],
            ['Nilson Santiz', 'PE', '11B', 3, 11],
            ['Nilson Santiz', 'PE', '07B', 4, 7],
            ['Nilson Santiz', 'PE', '11A', 4, 11],
            ['Nilson Santiz', 'PE', '09A', 5, 7],
            ['Nilson Santiz', 'PE', '08A', 5, 11],
            ['Paulo Álvarez', 'Cálculo', '11A', 1, 2],
            ['Paulo Álvarez', 'Trigonometría', '10B', 1, 3],
            ['Paulo Álvarez', 'Trigonometría', '10A', 1, 7],
            ['Paulo Álvarez', 'Cálculo', '11B', 1, 8],
            ['Paulo Álvarez', 'Trigonometría', '10B', 2, 1],
            ['Paulo Álvarez', 'Cálculo', '11B', 2, 2],
            ['Paulo Álvarez', 'Cálculo', '11A', 2, 6],
            ['Paulo Álvarez', 'Trigonometría', '10A', 2, 11],
            ['Paulo Álvarez', 'Cálculo', '11B', 3, 1],
            ['Paulo Álvarez', 'Cálculo', '11A', 3, 2],
            ['Paulo Álvarez', 'Trigonometría', '10B', 3, 3],
            ['Paulo Álvarez', 'Trigonometría', '10A', 3, 8],
            ['Paulo Álvarez', 'Cálculo', '11B', 4, 1],
            ['Paulo Álvarez', 'Cálculo', '11A', 4, 2],
            ['Paulo Álvarez', 'Trigonometría', '10A', 4, 3],
            ['Paulo Álvarez', 'Trigonometría', '10B', 4, 8],
            ['Paulo Álvarez', 'Trigonometría', '10B', 5, 3],
            ['Paulo Álvarez', 'Cálculo', '11B', 5, 6],
            ['Paulo Álvarez', 'Cálculo', '11A', 5, 8],
            ['Paulo Álvarez', 'Trigonometría', '10A', 5, 12],
            ['Samir Peñate', 'Sociales', '06A', 1, 1],
            ['Samir Peñate', 'Filosofía', '11B', 1, 3],
            ['Samir Peñate', 'Sociales', '06B', 1, 7],
            ['Samir Peñate', 'Sociales', '06A', 2, 2],
            ['Samir Peñate', 'Sociales', '06B', 2, 6],
            ['Samir Peñate', 'Sociales', '08A', 2, 11],
            ['Samir Peñate', 'Sociales', '07B', 2, 12],
            ['Samir Peñate', 'Sociales', '05A', 3, 1],
            ['Samir Peñate', 'Filosofía', '11A', 3, 7],
            ['Samir Peñate', 'Sociales', '08A', 3, 11],
            ['Samir Peñate', 'Sociales', '05A', 4, 1],
            ['Samir Peñate', 'Sociales', '08B', 4, 6],
            ['Samir Peñate', 'Sociales', '07A', 4, 11],
            ['Samir Peñate', 'Sociales', '07B', 5, 2],
            ['Samir Peñate', 'Sociales', '08B', 5, 11],
            ['Samir Peñate', 'Sociales', '07A', 5, 12],
            ['Santiago Charris', 'Estadística y Geometría', '09A', 1, 3],
            ['Santiago Charris', 'Estadística y Geometría', '07B', 1, 6],
            ['Santiago Charris', 'Álgebra', '08B', 1, 7],
            ['Santiago Charris', 'Álgebra', '08A', 1, 8],
            ['Santiago Charris', 'Estadística y Geometría', '09B', 2, 1],
            ['Santiago Charris', 'Álgebra', '08B', 2, 2],
            ['Santiago Charris', 'Estadística', '10A', 2, 3],
            ['Santiago Charris', 'Estadística y Geometría', '07A', 2, 6],
            ['Santiago Charris', 'Álgebra', '08A', 2, 8],
            ['Santiago Charris', 'Estadística y Geometría', '09A', 3, 1],
            ['Santiago Charris', 'Estadística y Geometría', '07A', 3, 2],
            ['Santiago Charris', 'Álgebra', '08A', 3, 3],
            ['Santiago Charris', 'Estadística y Geometría', '09B', 3, 6],
            ['Santiago Charris', 'Álgebra', '08B', 3, 8],
            ['Santiago Charris', 'Álgebra', '08B', 4, 1],
            ['Santiago Charris', 'Estadística y Geometría', '07B', 4, 3],
            ['Santiago Charris', 'Estadística', '10B', 4, 7],
            ['Santiago Charris', 'Álgebra', '08A', 4, 8],
            ['Santiago Charris', 'Álgebra', '08B', 5, 2],
            ['Santiago Charris', 'Álgebra', '08A', 5, 3],
            ['Santiago Charris', 'Estadística', '10B', 5, 7],
            ['Santiago Charris', 'Estadística', '10A', 5, 8],
            ['Yesid Olivares', 'Álgebra', '09B', 1, 2],
            ['Yesid Olivares', 'Álgebra', '09A', 1, 6],
            ['Yesid Olivares', 'Estadística', '11B', 1, 11],
            ['Yesid Olivares', 'Estadística', '11A', 1, 12],
            ['Yesid Olivares', 'Estadística y Geometría', '06A', 2, 1],
            ['Yesid Olivares', 'Estadística y Geometría', '08A', 2, 3],
            ['Yesid Olivares', 'Álgebra', '09A', 2, 6],
            ['Yesid Olivares', 'Álgebra', '09B', 2, 11],
            ['Yesid Olivares', 'Estadística', '11B', 2, 12],
            ['Yesid Olivares', 'Estadística y Geometría', '06A', 3, 1],
            ['Yesid Olivares', 'Estadística y Geometría', '06B', 3, 2],
            ['Yesid Olivares', 'Álgebra', '09B', 3, 3],
            ['Yesid Olivares', 'Álgebra', '09A', 3, 6],
            ['Yesid Olivares', 'Estadística', '11A', 3, 11],
            ['Yesid Olivares', 'Álgebra', '09B', 4, 1],
            ['Yesid Olivares', 'Álgebra', '09A', 4, 2],
            ['Yesid Olivares', 'Estadística y Geometría', '08B', 4, 8],
            ['Yesid Olivares', 'Estadística y Geometría', '08A', 4, 12],
            ['Yesid Olivares', 'Estadística y Geometría', '08B', 5, 6],
            ['Yesid Olivares', 'Estadística y Geometría', '06B', 5, 7],
            ['Yesid Olivares', 'Álgebra', '09A', 5, 11],
            ['Yesid Olivares', 'Álgebra', '09B', 5, 12],
        ];

        $franjaCache = [];
        $cargaCache = [];
        $omitidas = 0;

        foreach ($clases as [$nombreDocente, $nombreMateria, $nombreCurso, $diaSemana, $orden]) {
            // --- resolver franja horaria (con cache para no repetir consultas) ---
            $franjaKey = $diaSemana.'-'.$orden;
            if (!isset($franjaCache[$franjaKey])) {
                $franjaCache[$franjaKey] = DB::table('academico_franja_horaria')
                    ->where('id_anio_escolar', $idAnioEscolar)
                    ->where('id_dia_semana', $diaSemana)
                    ->where('orden', $orden)
                    ->value('id');
            }
            $idFranja = $franjaCache[$franjaKey];

            // --- resolver carga academica (con cache) ---
            $cargaKey = $nombreDocente.'|'.$nombreMateria.'|'.$nombreCurso;
            if (!isset($cargaCache[$cargaKey])) {
                $idDocente = Usuario::whereRaw("CONCAT(nombre, ' ', apellido) = ?", [$nombreDocente])->value('id_user');
                $idAsignatura = DB::table('academico_asignatura')->where('nombre', $nombreMateria)->value('id');
                $idCurso = DB::table('curso')->where('nombre', $nombreCurso)->value('id');

                $idCarga = null;
                if ($idDocente && $idAsignatura && $idCurso) {
                    $idDocenteAsignatura = DB::table('academico_docente_asignatura')
                        ->where('id_docente', $idDocente)
                        ->where('id_asignatura', $idAsignatura)
                        ->value('id');

                    if ($idDocenteAsignatura) {
                        $idCarga = DB::table('academico_carga_academica')
                            ->where('id_docente_asignatura', $idDocenteAsignatura)
                            ->where('id_curso', $idCurso)
                            ->value('id');
                    }
                }
                $cargaCache[$cargaKey] = $idCarga;
            }
            $idCarga = $cargaCache[$cargaKey];

            if (!$idFranja || !$idCarga) {
                $omitidas++;
                continue;
            }

            DB::table('academico_horario_clase')->updateOrInsert(
                [
                    'id_carga_academica' => $idCarga,
                    'id_franja_horaria'  => $idFranja,
                ],
                [
                    'tipo'       => 'CLASE',
                    'created_at' => now(),
                    'updated_at' => now(),
                ]
            );
        }

        if ($omitidas > 0) {
            $this->command?->warn("Horario: {$omitidas} filas omitidas por datos base faltantes.");
        }
    }
}
